theme: jekyll-theme-minimal
title: [Louise Kelly]
description: [Data Analytics and Society Integrated PhD student at the University of Manchester.]

markdown: kramdown
<!--permalink: /blog/:year/:month/:day/:title-->
